Document: 2ping
Title: Debian 2ping Manual
Author: <insert document author here>
Abstract: This manual describes what 2ping is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/2ping/2ping.sgml.gz

Format: postscript
Files: /usr/share/doc/2ping/2ping.ps.gz

Format: text
Files: /usr/share/doc/2ping/2ping.text.gz

Format: HTML
Index: /usr/share/doc/2ping/html/index.html
Files: /usr/share/doc/2ping/html/*.html
